const base='https://www.cs2tricks.com/nades/mirage/smokes/';
export const smokes=[
{id:'stairs',name:'跳台烟',en:'STAIRS',zone:'A',target:[5.7,13.4],origin:[39.1,-4.6],from:'T 出生点 · 木板旁',method:'静止跳投',keys:['左键','跳跃'],description:'封住跳台视野，为 A1 和 A2 的队友创造进点空间。',steps:['在 T 出生点通往 A 区方向的木板旁站定。','以脚手架上方的两段木结构为参照，对齐瞄点；具体位置见来源图示。','保持静止，按住左键准备投掷，跳起时松开左键。'],source:base+'stairs-from-t-spawn-0691',sourceName:'CS2Tricks · Kobrick',tip:'通常与拱门烟、警家烟配合使用；队友就位后再同步出手。',video:null},
{id:'jungle',name:'拱门烟',en:'JUNGLE',zone:'A',target:[-5.3,12.4],origin:[39.1,-4.6],from:'T 出生点 · 木板旁',method:'前移跳投',keys:['W','左键','跳跃'],description:'遮挡 Jungle 通往 A 包点的视线，减少进攻时需要处理的角度。',steps:['站在 T 出生点木板旁，按来源的站位图贴好位置。','瞄准对应屋顶转角；精确瞄点需对照来源图示。','按住左键，轻点 W 并跳投，松开左键释放烟雾弹。'],source:base+'jungle-from-t-spawn-29aa',sourceName:'CS2Tricks · Kobrick',tip:'这颗烟建议与跳台烟配合，单独使用不能封住整个横穿区域。',video:null},
{id:'ct',name:'警家烟',en:'CT / TICKET',zone:'A',target:[-4.1,29.4],origin:[41.86,-11.98],from:'T 出生点 · A 区方向',method:'静步移动跳投',keys:['Shift + W','左键','跳跃'],description:'封住警家售票亭方向，帮助队友进入 A 包点并完成下包。',steps:['使用来源的站位与瞄点图确定 T 出生点起始位置。','按住 Shift + W 静步前进，观察准星与电线的相对位置。','准星到达电线时，使用左键跳投。'],source:'https://www.cs2util.com/mirage/smoke/ct-smoke-from-t-spawn',sourceName:'CS2Util · CT Smoke From T Spawn',tip:'这是移动跳投版本，释放时机需要在练习地图中校准。',video:null},
{id:'window',name:'VIP 烟',en:'WINDOW',zone:'mid',target:[-8.8,-3.8],origin:[38.4,-16.2],targetHeight:.2,from:'T 出生点 · 门边角落',method:'蹲姿跳投',keys:['蹲下','左键','跳跃'],description:'遮挡中路窗口的架枪视野，让队友更容易争夺中路控制权。',steps:['在 T 出生点门旁的角落贴好站位。','找到悬挂地毯，瞄准从左数第二个标记，细节见来源图。','蹲下，按住左键准备，再起跳释放烟雾弹。'],source:base+'window-from-t-spawn-568d',sourceName:'CS2Tricks · StellaraQwQ',tip:'窗口烟只处理窗口视野，出中路时仍需留意拱门和 B 小。',video:null},
{id:'connector',name:'拱门下烟',en:'CONNECTOR',zone:'mid',target:[0.2,2.4],origin:[18.8,-27.2],from:'B 二楼外 · 楼梯旁',method:'静止跳投',keys:['左键','跳跃'],description:'封住拱门下口，帮助队友从中路推进或转向 B 小。',steps:['走到 B 二楼外，贴住公寓楼梯旁的角落。','对准地毯上两处标记之间的位置，参照来源图示确认。','站稳不移动，按住左键后跳起释放。'],source:base+'bottom-connector-from-outside-tv-189a',sourceName:'CS2Tricks · L1SSU',tip:'落点在拱门下口，与封 A 区 Jungle 的拱门烟不同。',video:null},
{id:'market',name:'超市窗口烟',en:'MARKET WINDOW',zone:'B',target:[-27.3,-11.3],origin:[12.5,-33.7],from:'B 后巷 · 墙角',method:'静止跳投',keys:['左键','跳跃'],description:'遮住超市窗口，切断该方向对 B 包点的直线视野。',steps:['在 B 后巷按来源站位图贴住墙角。','找到塔楼，以塔楼上边缘为瞄准参照；精确落点依赖站位。','保持静止，按住左键并跳投释放。'],source:base+'market-window-from-back-alley-15a4',sourceName:'CS2Tricks · Back Alley lineup',tip:'窗口烟不会同时封住超市门，进入 B 区时需单独处理门口。',video:null}
].map(s=>({...s,type:'smoke'}));

export const utilities=[...smokes,
{id:'flash-ramp',type:'flash',name:"A1 反清闪",en:"A RAMP",zone:'A',target:[18.8,17.1],origin:[16.4394,21.3406],gameOrigin:[151.96875,-1914.032471,-104.128754],from:"A 二楼下 · 木台附近",method:"静止跳投",keys:["左键","跳跃"],description:"从 A 二楼下向 A1 方向投闪，配合队友反清。",steps:["在 A 二楼下按来源站位图贴好位置。","瞄准木结构上较低的木点，对照来源瞄点图确认。","保持静止，按住左键并跳起释放。"],source:"https://www.cs2tricks.com/nades/mirage/flashbangs/a-ramp-from-underwood-a5de",sourceName:"CS2Tricks · A Ramp from Underwood",tip:"出手前提醒 A1 附近队友背闪；爆点位置为示意。",targetOffset:2.5,video:null},
{id:'flash-mid',type:'flash',name:"中路瞬爆闪",en:"MID POP FLASH",zone:'mid',target:[-7.4,-1.4],origin:[-11.5594,1.5406],gameOrigin:[-1247.96875,-924.031311,-103.96875],from:"VIP · 窗口内",method:"右键跳投",keys:["右键","跳跃"],description:"从窗口投出近距离闪光，为队友争夺中路创造时机。",steps:["在 VIP 内按来源站位图站定。","对照窗口瞄点图，使用右键准备近距离投掷。","保持静止，跳起时释放右键。"],source:"https://www.cs2util.com/mirage/flash/mid-instance-pop-flash-from-window",sourceName:"CS2Util · Mid Instant Pop Flash",tip:"与队友沟通拉出的时机；闪光效果受朝向和遮挡影响。",targetOffset:2,video:null},
{id:'flash-b',type:'flash',name:"B 区进点闪",en:"B SITE FLASH",zone:'B',target:[-25.2,-23.6],origin:[-16.0394,-30.2206],gameOrigin:[-1471.972412,664.031372,15.87125],from:"B 二楼 · 窗口",method:"静止左键投掷",keys:["左键"],description:"从 B 二楼窗口投闪，配合队友进入 B 包点。",steps:["在 B 二楼窗口按来源站位图站定。","对照来源瞄点，确认队友已准备好出二楼。","保持静止，左键投出，不跳跃。"],source:"https://www.cs2util.com/mirage/flash/b-flash-from-b-apartments-window",sourceName:"CS2Util · B Apartments Window Flash",tip:"先报闪再同步出点，避免影响已经落地的队友。",targetOffset:3,video:null},
{id:'he-default',type:'he',name:"A 默认包点雷",en:"A DEFAULT",zone:'A',target:[9.7,23.8],origin:[1.0394,8.1497],gameOrigin:[-618.031494,-1254.487183,-103.96875],from:"A 区 · 跳台附近",method:"静止左键投掷",keys:["左键"],description:"从跳台方向投向 A 默认包点，干扰下包或处理该位置。",steps:["按来源站位图在跳台附近站定。","对照来源瞄点，瞄向默认包点方向。","保持静止，左键投出，不跳跃。"],source:"https://www.cs2util.com/mirage/grenade/default-grenade-from-stairs",sourceName:"CS2Util · Default Grenade From Stairs",tip:"先确认目标位置；示意范围不代表实际伤害范围。",video:null},
{id:'he-underpass',type:'he',name:"下水道雷",en:"UNDERPASS",zone:'mid',target:[-6,-11.5],origin:[-1.6408,-22.7615],gameOrigin:[-752.037964,291.074371,-102.090073],from:"B 小 · 下水道上方",method:"前跑两步投掷",keys:["W","左键"],description:"从 B 小向下水道投雷，处理下层通道。",steps:["按来源站位图在 B 小站好位置。","对准来源瞄点，按住左键准备。","向前跑两步后释放左键，不跳跃。"],source:"https://www.cs2util.com/mirage/grenade/underpass-grenade-from-b-short",sourceName:"CS2Util · Underpass Grenade From B Short",tip:"这是下层目标，旋转地图或调低剖切高度查看通道。",video:null},
{id:'he-window',type:'he',name:"VIP 窗口雷",en:"WINDOW HE",zone:'mid',target:[-8.8,-3.8],origin:[23.4594,-3.3971],gameOrigin:[502.968445,-677.147095,-96.669907],from:"中路 · 沙袋箱旁",method:"前跑两步投掷",keys:["W","左键"],description:"从中路箱子附近向 VIP 窗口投雷。",steps:["按来源站位图在中路箱旁站好位置。","瞄向窗口，对照来源图校准高度。","向前跑两步后释放左键，不跳跃。"],source:"https://www.cs2util.com/mirage/grenade/mid-window-grenade-from-mid-boxes",sourceName:"CS2Util · Mid Window Grenade",tip:"窗口遮挡与烟雾会影响实战效果，先在练习服确认。",video:null},
{id:'fire-default',type:'molotov',name:"A 默认包点火",en:"A DEFAULT FIRE",zone:'A',target:[9.7,23.8],origin:[1.0394,8.1497],gameOrigin:[-618.031494,-1254.487183,-104.128754],from:"A 区 · 跳台附近",method:"静止左键投掷",keys:["左键"],description:"从跳台方向投火，限制默认包点附近的停留空间。",steps:["按来源站位图在跳台附近站定。","对照来源瞄点，瞄向默认包点方向。","保持静止，左键投出，不跳跃。"],source:"https://www.cs2util.com/mirage/molotov/default-molotov-from-stairs",sourceName:"CS2Util · Default Molotov From Stairs",tip:"火焰铺展为示意，实际覆盖受地形和道具类型影响。",video:null},
{id:'fire-van',type:'molotov',name:"B 白车火",en:"VAN FIRE",zone:'B',target:[-32.4,-27.7],origin:[-9.2376,-30.7749],gameOrigin:[-1131.880371,691.74292,-15.96875],from:"B 二楼 · 走廊",method:"蹲姿左键投掷",keys:["蹲下","左键"],description:"从 B 二楼向白车投火，帮助队友清理白车附近。",steps:["在 B 二楼按来源站位图站好位置。","蹲下，对照来源瞄点瞄向白车方向。","保持蹲姿，左键投出，不跳跃。"],source:"https://www.cs2util.com/mirage/molotov/van-molotov",sourceName:"CS2Util · Van Molotov",tip:"与进点闪配合使用；先确认白车附近队友的位置。",video:null},
{id:'fire-window',type:'molotov',name:"VIP 窗口火",en:"WINDOW FIRE",zone:'mid',target:[-8.8,-3.8],origin:[23.4593,-3.4223],gameOrigin:[502.966339,-675.885925,-96.669968],from:"中路 · 沙袋箱旁",method:"前跑两步投掷",keys:["W","左键"],description:"从中路箱子附近向窗口投火，迫使窗口架枪位移动。",steps:["按来源站位图贴住中路箱旁的位置。","对照来源瞄点图校准准星。","向前跑两步后释放左键，不跳跃。"],source:"https://www.cs2util.com/mirage/molotov/mid-window-molotov-from-mid-boxes",sourceName:"CS2Util · Mid Window Molotov",tip:"先确认窗口是否有烟；地图动画不模拟灭火或反弹。",video:null}
];
